services:
  - type: web
    name: faruk-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    healthCheckPath: /
    autoDeploy: true
